/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 guy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Person(props) {
  const { nodes, materials } = useGLTF('/models/guy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface11_polySurface12.geometry} material={materials.initialShadingGroup} />
      <mesh geometry={nodes.polySurface11_polySurface12_1.geometry} material={materials.initialShadingGroup} />
      <mesh geometry={nodes.polySurface13_polySurface14.geometry} material={materials.initialShadingGroup} />
      <mesh geometry={nodes.polySurface13_polySurface14_1.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

useGLTF.preload('/models/guy.glb')
